apiVersion: v1
kind: ConfigMap
metadata:
  name: crudio-config
  namespace: crudio-local
data:
  # Postgres
  POSTGRES_DB: "appdb"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"

  # MongoDB
  MONGO_DB: "appdb_logs"
  MONGO_HOST: "mongodb"
  MONGO_PORT: "27017"

  # Redis
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"

  # JWT
  JWT_ISSUER: "CrudIo.Api"
  JWT_AUDIENCE: "CrudIo.Client"
  JWT_EXPIRATION_MINUTES: "60"
  CLIENT_ACCESS_TOKEN_EXPIRATION_MINUTES: "15"
  CLIENT_REFRESH_TOKEN_EXPIRATION_DAYS: "30"