apiVersion: v1
kind: Secret
metadata:
  name: crudio-secrets
  namespace: crudio-local
type: Opaque
stringData:
  POSTGRES_PASSWORD: "appuser"
  MONGO_ROOT_PASSWORD: "appuser"
  MONGO_ROOT_USERNAME: "appuser"
  REDIS_PASSWORD: "appuser"
  JWT_SECRET: "6Y59~2+(]G4!r/k_;1*<p;1u^Q>U=wXn5m3V}F1k9?-D&,C+^$\\j_9c7R9r[/Q^XC6U^:hDJ"
  CLIENT_API_KEY: "&,M:8<bi|5=NmnG&P?dJ=ibriyx|6bG|V/r+p-D&#c:p84N)=2"
  # Client ID and name are non-sensitive, can go in ConfigMap
  CLIENT_ID: "crudio-client"
  CLIENT_NAME: "CrudIo Integration"
